
- name: helm gw
  kubernetes.core.helm:
    host: "{{ openshift_url }}"
    api_key: "{{openshift_token}}"
    validate_certs: "{{ openshift_valcerts }}"
    chart_repo_url: "{{ helmchart_url }}"
    chart_ref: "{{ helmchart_ref }}"
    chart_version: "{{ helmchart_version }}"
    release_name: "{{ item.name }}"
    release_namespace: "{{ helmchart_namespace }}"
    release_values: "{{ lookup('template', 'valuesgw.yaml.tpl') | from_yaml }}"
    release_state: "{{ helmchart_state }}"
  loop: "{{ helmchart_gwelement }}"
  loop_control:
    label: "{{ item.name }}"
- name: helm gw
  kubernetes.core.helm:
    host: "{{ openshift_url }}"
    api_key: "{{openshift_token}}"
    validate_certs: "{{ openshift_valcerts }}"
    chart_repo_url: "{{ helmchart_url }}"
    chart_ref: "{{ helmchart_ref }}"
    chart_version: "{{ helmchart_version }}"
    release_name: "{{ item.name }}"
    release_namespace: "{{ helmchart_namespace }}"
    release_values: "{{ lookup('template', 'values.yaml.tpl') | from_yaml }}"
    release_state: "{{ helmchart_state }}"
  loop: "{{ helmchart_elements }}"
  loop_control:
    label: "{{ item.name }}"