---
version: 1
build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-23/ee-minimal-rhel8:latest'
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
additional_build_steps:
  prepend: ADD _build/ansible.cfg ansible.cfg
  append: RUN ansible-galaxy collection list